name: Docker Build Business Service
on:
  workflow_dispatch:
    inputs:
      micro-service:
        description: 'micro-services'
        required: true
        type: choice
        options: 
        - business-service
        - collection-service
        - dashboard-analytics
        - egf-instrument
        - billing-service
        - dashboard-analytics
        - dashboard-ingest
        - egov-hrms
        - egov-accesscontrol
        - egov-common-masters
        - egov-data-uploader
        - egov-document-uploader
        - egov-enc-service
        - egov-filestore
        - egov-idgen
        - egov-indexer
        - egov-localization
        - egov-location
        - egov-mdms-service
        - egov-notification-mail
        - egov-notification-sms
        - egov-otp
        - egov-persister
        - egov-pg-service
        - egov-searcher
        - egov-survey-services
        - egov-telemetry
        - egov-url-shortening
        - egov-user
        - egov-workflow-v2
        - national-dashboard-ingest
        - national-dashboard-kafka-pipeline
        - nlp-engine
        - pdf-service
        - report
        - service-request
        - user-otp
        - zuul

  
jobs:
  Docker_Build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      app_docker_file: business-services/build/maven/Dockerfile
      app_docker_context: business-services/${{inputs.micro-service}}
      service: business-services
      micro-service: ${{inputs.micro-service}}
      db_docker_file: business-services/${{inputs.micro-service}}/src/main/resources/db/Dockerfile
      db_docker_context: business-services/${{inputs.micro-service}}/src/main/resources/db
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          
      
  kubectl_deployment_app:
    needs: Docker_Build
    uses: ./.github/workflows/k8-deploy.yaml
    with:
      DEPLOYMENT_NAME: ${{ inputs.micro-service }}
      DB_DEPLOYMENT: ${{ needs.Docker_Build.outputs.db_build }}
      APP_DOCKER_REPO: velsof/velsof-${{ inputs.micro-service }}-app:${{ needs.Docker_Build.outputs.tag }}
      DB_DOCKER_REPO: velsof/velsof-${{inputs.micro-service}}-db:${{ needs.Docker_Build.outputs.tag }}
    secrets:
      K3D_KUBE_CONFIG: ${{ secrets.K3D_KUBE_CONFIG }}