name: Docker Build
on:
  workflow_call:
    inputs:
      FILE:
        required: true
        type: string
      CONTEXT: 
        required: true
        type: string
      DOCKER_REPO:
        required: true
        type: string
               
    secrets:
      DOCKERHUB_USERNAME:
       required: true
      DOCKERHUB_TOKEN:
       required: true
       
env: 
  FILE: ${{ inputs.FILE }}
  CONTEXT: ${{ inputs.CONTEXT }}
  DOCKER_REPO: ${{ inputs.DOCKER_REPO }}
  
jobs:
  # Docker Build
  Docker_Build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
      
      # Extract branch for docker tag
      - name: Get branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      # Login To Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Get Short commit
      - name: Get short commit
        id: commit
        uses: prompt/actions-commit-hash@v3
      
      # Build the Docker image
      - name: Build and push
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
        with:
          push: true
          tags: ${{ env.DOCKER_REPO}}:${{ steps.commit.outputs.short }}
          file: ${{ env.FILE}}
          context: ${{ env.CONTEXT}}