name: Docker Build Muncipal service

on:
  workflow_dispatch:
    inputs:
      micro-service:
        description: 'micro-services'
        required: true
        type: choice
        options: 
        - birth-death-services
        - bpa-calculator
        - bpa-services
        - echallan-services
        - echallan-calculator
        - fsm-calculator


jobs:
  Docker_Build_App:
    uses: ./.github/workflows/docker-build.yaml
    with:
      app_docker_file: municipal-services/build/maven/Dockerfile
      app_docker_context: municipal-services/${{inputs.micro-service}}
      service: municipal-services
      micro-service: ${{inputs.micro-service}}
      db_docker_file: municipal-services/${{inputs.micro-service}}/src/main/resources/db/Dockerfile
      db_docker_context: municipal-services/${{inputs.micro-service}}/src/main/resources/db
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          
      
  # kubectl_deployment_app:
  #   needs: Docker_Build_App
  #   if: ${{ needs.Docker_Build_App.outputs.db_path == 'absent' }}
  #   uses: ./.github/workflows/k8-deploy.yaml
  #   with:
  #     DEPLOYMENT_NAME: ${{ inputs.micro-service }}
  #     DOCKER_REPO: velsof/velsof-${{ inputs.micro-service }}-app:${{ needs.Docker_Build_App.outputs.tag }}
  #   secrets:
  #     K3D_KUBE_CONFIG: ${{ secrets.K3D_KUBE_CONFIG }}
      
  # kubectl_deployment_db:
  #   needs: Docker_Build_App
  #   if: ${{ needs.Docker_Build_App.outputs.db_path == 'present' }}
  #   uses: ./.github/workflows/k8-deploy.yaml
  #   with:
  #     DEPLOYMENT_NAME: ${{ inputs.micro-service }}
  #     DB_DEPLOYMENT: true
  #     DOCKER_REPO: velsof/velsof-${{inputs.micro-service}}-app:${{ needs.Docker_Build_App.outputs.tag }}
  #     DB_DOCKER_REPO: velsof/velsof-${{inputs.micro-service}}-db:${{ needs.Docker_Build_App.outputs.tag }}
  #   secrets:
  #     K3D_KUBE_CONFIG: ${{ secrets.K3D_KUBE_CONFIG }}
