name: Docker Build Muncipal service

on:
  workflow_dispatch:
    inputs:
      micro-service:
        description: 'micro-services'
        required: true
        type: choice
        options: 
        - birth-death-services
        - bpa-calculator
        - bpa-services
        - echallan-calculator
        - echallan-services
        - egov-user-event
        - firenoc-calculator
        - firenoc-services
        - fsm-calculator
        - fsm
        - inbox
        - land-services
        - noc-services
        - pgr-services
        - property-services
        - pt-calculator-v2
        - pt-services-v2
        - rainmaker-pgr
        - sw-calculator
        - sw-services
        - tl-calculator
        - tl-services
        - turn-io-adapter
        - vehicle
        - vendor
        - ws-calculator
        - ws-services
      deploy_to:
        description: "env"
        required: true
        type: choice
        options:
          - dev
          - test


jobs:
  Docker_Build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      app_docker_file: municipal-services/build/maven/Dockerfile
      app_docker_context: municipal-services/${{inputs.micro-service}}
      service: municipal-services
      micro-service: ${{inputs.micro-service}}
      env: ${{inputs.deploy_to}}
      db_docker_file: municipal-services/${{inputs.micro-service}}/src/main/resources/db/Dockerfile
      db_docker_context: municipal-services/${{inputs.micro-service}}/src/main/resources/db
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          
      
  kubectl_deployment:
    needs: Docker_Build
    uses: ./.github/workflows/k8-deploy.yaml
    with:
      DEPLOYMENT_NAME: ${{ inputs.micro-service }}
      env: ${{inputs.deploy_to}}
      DB_DEPLOYMENT: ${{ needs.Docker_Build.outputs.db_build }}
      APP_DOCKER_REPO: velsof/velsof-${{ inputs.micro-service }}-app:${{ needs.Docker_Build.outputs.tag }}
      DB_DOCKER_REPO: velsof/velsof-${{inputs.micro-service}}-db:${{ needs.Docker_Build.outputs.tag }}
    secrets:
      K3D_KUBE_CONFIG: ${{ secrets.K3D_KUBE_CONFIG }}