name: Docker Build
on:
  push:
    branches:
      - 2.0-velsof-fsm
  
jobs:
  # Docker Build
  Docker_Build_App:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
      
      # Extract branch for docker tag
      - name: Get branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      # Login To Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Get Short commit
      - name: Get short commit
        id: commit
        uses: prompt/actions-commit-hash@v3
      
      # Get Short commit
      - name: Copy start.sh
        run: sudo cp municipal-services/build/maven/start.sh municipal-services/bpa-calculator
      
      # Build the Docker image
      - name: Build and push
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
        with:
          push: true
          tags: velsof/velsof-bpa-calculator-app:${{ steps.commit.outputs.short }}
          file: municipal-services/build/maven/Dockerfile
          context: municipal-services/bpa-calculator

      - name: Check DB docker file path
        id: db_path
        run: | 
          if [ -d "municipal-services/bpa-calculator/src/main/resources/db" ]; then echo "path=present" >> $GITHUB_OUTPUT; else echo "path=absent" >> $GITHUB_OUTPUT; fi

      - name: echo
        run: echo ${{ steps.db_path.outputs.path }}
      # - name: Build and push
      #   if: ${{ steps.db_path.outputs.path }} == 'present' 
      #   uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
      #   with:
      #     push: true
      #     tags: velsof/velsof-bpa-calculator-db:${{ steps.commit.outputs.short }}
      #     file: municipal-services/bpa-calculator/src/main/resources/db/Dockerfile
      #     context: municipal-services/bpa-calculator/src/main/resources/db
